name: Build Examples

on:
  pull_request:
    types: [labeled]
jobs:
  build-examples:
    strategy:
      matrix:
        example:
          - Async-Server
          - Authentication
          - HTML-Forms
          - HTTPS-and-HTTP
          - Middleware
          - Parameters
          - Parameter-Validation
          - Put-Post-Echo
          - REST-API
          - Self-Signed-Certificate
          - Static-Page
          - Websocket-Chat
        board:
          - wrover
          - wroom
    runs-on: ubuntu-latest
    if: "contains( github.event.pull_request.labels.*.name, 'CI: Build Examples' )"
    steps:
    - name: Checkout codebase
      uses: actions/checkout@f90c7b395dac7c5a277c1a6d93d5057c1cddb74e
    - name: Set up Python
      uses: actions/setup-python@9ac730844c47e52575257e93faf193c4530bc095
      with:
        python-version: '3.8'
    - name: Install PlatformIO
      run: |
        python -m pip install --upgrade pip
        pip install platformio
    - name: Build example
      run: ./extras/ci/scripts/build-example.sh ${{ matrix.board }} ${{ matrix.example }}
  remove-label:
    runs-on: ubuntu-latest
    if: "contains( github.event.pull_request.labels.*.name, 'CI: Build Examples' )"
    steps:
    - name: Remove Label from PR
      uses: octokit/request-action@57ec46afcc4c58c813af3afe67e57ced1ea9f165
      with:
        route: DELETE /repos/:repository/issues/:issue_number/labels/:name
        repository: ${{ github.repository }}
        issue_number: ${{ github.event.number }}
        name: "CI%3A Build Examples"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      